# Generated by Django 5.1.5 on 2025-01-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student_tb',
        ),
    ]
